<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>DoenaSoft.JsonFragmentParser</AssemblyName>
		<RootNamespace>DoenaSoft.JsonFragmentParser</RootNamespace>
		<TargetFrameworks>netstandard2.0;net472;net10.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/DJDoena/DoenaSoft.UnitsOfMeasurement</PackageProjectUrl>
		<RepositoryUrl>https://github.com/DJDoena/DoenaSoft.UnitsOfMeasurement</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>json; parser</PackageTags>
		<PackageIcon>djdsoft.png</PackageIcon>
		<Product>JSON Fragment Parser</Product>
		<Company>Doena Soft.</Company>
		<Authors>DJ Doena</Authors>
		<Copyright>2024 - 2026</Copyright>
		<Version>1.0.1</Version>
		<Description>Extracts complete JSON objects or arrays from the beginning of text, stopping once a valid fragment is found, and parses them into navigable tree structures.</Description>
		<PackageIconUrl />
	</PropertyGroup>

	<ItemGroup>
		<None Include="djdsoft.png" Pack="true" PackagePath="\" />
		<None Include="..\readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>